/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manajemen_data_guru;

import java.sql.*;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.text.ParseException;


/**
 *
 * @author lenov
 */
public class tambahguru extends javax.swing.JFrame {
    
    private HomePage_mdg parent;

    public tambahguru(HomePage_mdg parent) {
        this.parent = parent;
        initComponents();
    }

    public static void tambahDataGuru(String idGuru, String nama, String tanggalLahir, String jenisKelamin, String mataPelajaran, String statusGuru) {
    
    // Koneksi ke database melalui DatabaseConnection_mdg class
        Connection conn = null;
        PreparedStatement stmtGuru = null;

    /**
     * Creates new form tambahguru
     */
    try {
            // Menggunakan koneksi dari DatabaseConnection_mdg
            conn = DatabaseConnection_mdg.connect();  // Replace `getConnection` with `connect()`

            // Validasi input format tanggal
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            sdf.parse(tanggalLahir);

            // Query untuk memasukkan data ke tabel guru
            String queryGuru = "INSERT INTO guru (idGuru, nama, tanggalLahir, jenisKelamin, mataPelajaran, statusGuru) "
                               + "VALUES (?, ?, ?, ?, ?, ?)";

            stmtGuru = conn.prepareStatement(queryGuru);
            stmtGuru.setString(1, idGuru);
            stmtGuru.setString(2, nama);
            stmtGuru.setString(3, tanggalLahir);
            stmtGuru.setString(4, jenisKelamin);
            stmtGuru.setString(5, mataPelajaran);
            stmtGuru.setString(6, statusGuru); // Store statusGuru directly in the `guru` table
            stmtGuru.executeUpdate();

            JOptionPane.showMessageDialog(null, "Data berhasil ditambahkan!");

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Format tanggal salah! Gunakan format YYYY-MM-DD.");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        } finally {
            try {
                if (stmtGuru != null) stmtGuru.close();
                if (conn != null) conn.close();  // Ensure connection is properly closed
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbjeniskelamin = new javax.swing.JComboBox<>();
        txttgllahir = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbstatusguru = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtmapel = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtidguru = new javax.swing.JTextField();
        btnsimpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setText("Aplikasi Management Data Guru");

        jLabel2.setText("Nama Lengkap");

        txtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis Kelamin");

        jLabel8.setText("Tanggal Lahir");

        cmbjeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-Laki", "Perempuan" }));
        cmbjeniskelamin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbjeniskelaminActionPerformed(evt);
            }
        });

        txttgllahir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttgllahirActionPerformed(evt);
            }
        });

        jLabel6.setText("Status Guru");

        cmbstatusguru.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tetap", "Honorer" }));
        cmbstatusguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbstatusguruActionPerformed(evt);
            }
        });

        jLabel5.setText("Mata Pelajaran");

        jLabel7.setText("ID Guru");

        txtidguru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidguruActionPerformed(evt);
            }
        });

        btnsimpan.setBackground(new java.awt.Color(0, 0, 255));
        btnsimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnsimpan.setText("Simpan");
        btnsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsimpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(146, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cmbstatusguru, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmapel, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtidguru, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txttgllahir))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(cmbjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(142, 142, 142))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtidguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttgllahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbjeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(txtmapel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbstatusguru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(btnsimpan)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnamaActionPerformed

    private void cmbjeniskelaminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbjeniskelaminActionPerformed

    }//GEN-LAST:event_cmbjeniskelaminActionPerformed

    private void cmbstatusguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbstatusguruActionPerformed

    }//GEN-LAST:event_cmbstatusguruActionPerformed

    private void txtidguruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidguruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidguruActionPerformed

    private void txttgllahirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttgllahirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttgllahirActionPerformed

    private void btnsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsimpanActionPerformed

        // Ambil data dari form
        String idGuru = txtidguru.getText();
        String nama = txtnama.getText();
        String tanggalLahir = txttgllahir.getText();
        String jenisKelamin = (String) cmbjeniskelamin.getSelectedItem();
        String mataPelajaran = txtmapel.getText();
        String statusGuru = (String) cmbstatusguru.getSelectedItem();

        // Validasi input data
        if (idGuru.isEmpty() || nama.isEmpty() || tanggalLahir.isEmpty() || mataPelajaran.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap isi semua kolom!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            // Panggil metode untuk menambah data guru
            tambahDataGuru(idGuru, nama, tanggalLahir, jenisKelamin, mataPelajaran, statusGuru);
            
            // Perbarui tabel di form utama
            parent.updateTabelGuru(); // Pastikan HomePage_mdg memiliki method updateTabelGuru()

            // Tutup form tambah guru
            this.dispose();
            new HomePage_mdg().setVisible(true);  // Ganti dengan class Login Anda
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnsimpanActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsimpan;
    private javax.swing.JComboBox<String> cmbjeniskelamin;
    private javax.swing.JComboBox<String> cmbstatusguru;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtidguru;
    private javax.swing.JTextField txtmapel;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttgllahir;
    // End of variables declaration//GEN-END:variables
}
